In [26]:
import pandas as pd

In [27]:
#Original "SEP-28k-Extended_clips.csv" file with all the extra columns
df_full_extended = pd.read_csv("SEP-28k-Extended_clips.csv")

In [29]:
df_full_extended.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28177 entries, 0 to 28176
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Show                   28177 non-null  object
 1   EpId                   28177 non-null  int64
 2   ClipId                 28177 non-null  int64
 3   Start                  28177 non-null  int64
 4   Stop                   28177 non-null  int64
 5   is_probably_host       28017 non-null  object
 6   speaker                28017 non-null  object
 7   clip_silhouette_score  26055 non-null  float64
 8   SEP12k                 12804 non-null  object
 9   SEP28k-E               28177 non-null  object
 10  SEP28k-T               28177 non-null  object
 11  SEP28k-D               28177 non-null  object
 12  Unsure                 28177 non-null  int64
 13  PoorAudioQuality       28177 non-null  int64
 14  Prolongation           28177 non-null  int64
 15  Block                  28177 non-null  int64
 16  SoundRep               28177 non-null  int64
 17  WordRep                28177 non-null  int64
 18  DifficultToUnderstand  28177 non-null  int64
 19  Interjection           28177 non-null  int64
 20  NoStutteredWords       28177 non-null  int64
 21  NaturalPause           28177 non-null  int64
 22  Music                  28177 non-null  int64
 23  NoSpeech               28177 non-null  int64
dtypes: float64(1), int64(16), object(7)
memory usage: 5.2+ MB

In [30]:
#Dropping unnecessary columns
df_extended = df_full_extended.drop(columns=["Start","Stop","is_probably_host","speaker","clip_silhouette_score","SEP12k","SEP28k-E","Unsure","PoorAudioQuality","DifficultToUnderstand","NaturalPause","Music","NoSpeech"])

In [31]:
#Remaining columns (including Train/Test Split columns):
#Show	EpId	ClipId	SEP28k-T	SEP28k-D	Prolongation	Block	SoundRep	WordRep	Interjection	NoStutteredWords
df_extended

,Show,EpId,ClipId,SEP28k-T,SEP28k-D,Prolongation,Block,SoundRep,WordRep,Interjection,NoStutteredWords
0,HeStutters,0,0,test,test,0,0,0,0,0,3
1,HeStutters,0,1,test,test,0,0,0,0,0,3
2,HeStutters,0,2,test,test,0,0,0,0,0,3
3,HeStutters,0,3,test,test,1,0,0,0,0,2
4,HeStutters,0,4,test,test,0,0,0,0,0,3
...,...,...,...,...,...,...,...,...,...,...,...
28172,WomenWhoStutter,109,35,dev,train,0,0,0,0,3,3
28173,WomenWhoStutter,109,36,test,test,1,1,3,0,1,0
28174,WomenWhoStutter,109,37,test,test,0,0,0,0,3,3
28175,WomenWhoStutter,109,38,test,test,1,0,0,0,3,2
28176,WomenWhoStutter,109,39,dev,train,0,0,0,0,0,3

In [34]:
#map Show EpId ClipID to a filepath column
def toFilePath (row):
    show = str(row["Show"])
    episode = str(row["EpId"])
    clip = str(row["ClipId"])

    return f"SEP-28k_CLIP/{show}/{episode}/{show}_{episode}_{clip}.wav"

In [35]:

df_extended["filepath"] = df_extended.apply(toFilePath,axis=1)#apply function row-by-row and create a new filepath column

In [37]:
df_extended.head()

,Show,EpId,ClipId,SEP28k-T,SEP28k-D,Prolongation,Block,SoundRep,WordRep,Interjection,NoStutteredWords,filepath
0,HeStutters,0,0,test,test,0,0,0,0,0,3,SEP-28k_CLIP/HeStutters/0/HeStutters_0_0.wav
1,HeStutters,0,1,test,test,0,0,0,0,0,3,SEP-28k_CLIP/HeStutters/0/HeStutters_0_1.wav
2,HeStutters,0,2,test,test,0,0,0,0,0,3,SEP-28k_CLIP/HeStutters/0/HeStutters_0_2.wav
3,HeStutters,0,3,test,test,1,0,0,0,0,2,SEP-28k_CLIP/HeStutters/0/HeStutters_0_3.wav
4,HeStutters,0,4,test,test,0,0,0,0,0,3,SEP-28k_CLIP/HeStutters/0/HeStutters_0_4.wav

In [38]:
df_extended.to_csv("SEP-28k-Filtered_with_Split_and_Path.csv")

In [39]:
#Split entries based on SEP28k-T SEP
T_train_df = df_extended[df_extended["SEP28k-T"]== 'train']
T_dev_df = df_extended[df_extended["SEP28k-T"]== 'dev']
T_test_df = df_extended[df_extended["SEP28k-T"]== 'test']

In [40]:
#Split entries based on SEP28k-D SEP
D_train_df = df_extended[df_extended["SEP28k-D"]== 'train']
D_dev_df = df_extended[df_extended["SEP28k-D"]== 'dev']
D_test_df = df_extended[df_extended["SEP28k-D"]== 'test']